line:
  vty:
    connection: vty
    vty04:
      login: local
      option: input
      protocol: ssh
      start: 0
      end: 4
      
      # experimental
      raw_config_line:
        - login local
        - transport input ssh
      raw: 
        login local
        transport input ssh
    vty515:
      login: local
      protocol: ssh
      option: input
      start: 5    
      end: 15
    vty01:
      login: local
      option: input
      protocol: ssh
      start: 0
      end: 4
      raw_config_line:
        - login local
        - transport input ssh
    vty25:
      login: local
      protocol: ssh
      option: input
      start: 5    
      end: 15

  con:
    connection: console
    con0:
      start: 0
      end: 0
      raw_config_line:
        - privilege level 15
        - logging synchronous
        - exec-timeout 0 0
  aux:
    connection: auxiliary
    aux0:
      start: 0
      end: 0
      raw_config_line:
        - privilege level 15
        - logging synchronous
        - exec-timeout 0 0
