---
- hosts: localhost
  gather_facts: no
  vars:
    some_integer: 5
    some_other_integer: "{{ some_integer }}"
  tasks:
    - debug: var=some_integer
    - debug: var=some_other_integer
    - name: assert some_integer and some_other_integer is an int 5 and not a string "5"
      assert:
          that:
              - some_integer == 5
              - some_other_integer == 5

    - name: assert some_int is not a string
      assert:
          that:
              - some_integer != "5"
              - some_other_integer != "5"

