#
vars:
  config:
    cur_conf_size           : "{{ item[0].cur_conf_size }}"
    version                 : "{{ item[1].version }}"
    timestamps_log          : "{{ item[2].timestamps_log }}"
    timestamps_debug        : "{{ item[3].timestamps_debug }}"
    pass_encrypt_set        : "{{ item[4].pass_encrypt_set }}"
    hostname                : "{{ item[5].hostname }}"
    ena_secret_value        : "{{ item[6].ena_secret_value }}"
    ena_secret_fingerprint  : "{{ item[6].ena_secret_fingerprint }}"
    clock_timezone          : "{{ item[7].clock_timezone }}"
    ip_dhcp_snooping_vlan   : "{{ item[8].ip_dhcp_snooping_vlan }}"
    vtp_mode                : "{{ item[9].vtp_mode }}"
    spanning_tree_mode      : "{{ item[10].spanning_tree_mode }}"
    spanning_tree_extend    : "{{ item[11].spanning_tree_extend }}"
    spanning_vlan_status    : "{{ item[12].spanning_vlan_status }}"
    spanning_tree_vlan      : "{{ item[12].spanning_tree_vlan }}"
    viap                    : "{{ item[13].viap }}"
    ip_http_server_stats    : "{{ item[14].ip_http_server_stats }}"
    ip_https_server_stats   : "{{ item[15].ip_https_server_stats }}"
    log_severity_lvl        : "{{ item[16].log_severity_lvl }}"
    log_facility            : "{{ item[17].log_facility }}"
    log_hostname            : "{{ item[18].log_hostname }}"
    snmp_srv_community      : "{{ item[19].snmp_srv_community }}"
    snmp_srv_location       : "{{ item[20].snmp_srv_location }}"
    snmp_srv_contact        : "{{ item[21].snmp_srv_contact }}"
    ntp_server_addr         : "{{ item[22].ntp_server_addr }}"
    ip_def_gw               : "{{ item[23].ip_def_gw }}"
    ip_domain_name          : "{{ item[24].ip_domain_name }}"

keys: 
  configs:
    value: "{{ config }}"
    start_block: "^Building.*" 
    end_block: ".*transport input ssh$" #".*end$"
    items:
      - "(Build\\w+).*\\n*(\\n|Current configuration \\W* )(?P<cur_conf_size>\\d*)"
      - "version (?P<version>.*)"
      - "service timestamps log (?P<timestamps_log>.*)"
      - "service timestamps debug (?P<timestamps_debug>.*)"
      - "(?P<pass_encrypt_set>.*)service password-encryption"
      - "hostname (?P<hostname>.*)"
      - "enable secret (?P<ena_secret_value>\\d) (?P<ena_secret_fingerprint>.*)"
      - "clock timezone (?P<clock_timezone>.*)"
      - "ip dhcp snooping vlan (?P<ip_dhcp_snooping_vlan>.*)"
      - "vtp mode (?P<vtp_mode>.*)"
      - "spanning-tree mode (?P<spanning_tree_mode>.*)"
      - "spanning-tree extend (?P<spanning_tree_extend>.*)"
      - "(?P<spanning_vlan_status>no |)spanning-tree vlan (?P<spanning_tree_vlan>.*\\d)"
      - "vlan internal allocation policy (?P<viap>.*)"
      - "(?P<ip_http_server_stats>no|) ip http server"
      - "(?P<ip_https_server_stats>no|) ip http secure-server"
      - "logging trap (?P<log_severity_lvl>.*)"
      - "logging facility (?P<log_facility>.*)"
      - "logging host (?P<log_hostname>.*)"
      - "snmp-server community (?P<snmp_srv_community>.*)"
      - "snmp-server location (?P<snmp_srv_location>.*)"
      - "snmp-server contact (?P<snmp_srv_contact>.*)"
      - "ntp server (?P<ntp_server_addr>.*)"
      - "ip default-gateway (?P<ip_def_gw>.*)"
      - "ip domain name (?P<ip_domain_name>.*)"
    