#
vars:
  status:
    device_id         : "{{ item.a }}"
    local_interface   : "{{ item.b | replace('Fas','FastEthernet')| replace('Gig','GigabitEthernet')| replace('Ten','Ten-GigabitEthernet')}}"
    holdtime          : "{{ item.c }}"
    capability        : "{{(item.d | replace('r','repeater')| replace('  ','')| replace('R','Router')| replace('S','Switch')| replace('B','Source-Route-Bridge')| replace('D','Remote')| replace('T','Trans-Bridge')| replace('H','Host')| replace('C','CVTA')| replace('M','Two-port-Mac-Relay') | replace('I','IGMP')).split(' ')}}"
    platform          : "{{ item.e }}"
    port_id           : "{{ item.f | replace('Fas','FastEthernet')| replace('Gig','GigabitEthernet')| replace('Ten','Ten-GigabitEthernet')}}"
keys:
  show_nei:
    value: "{{ status }}"
    items: "^(?P<a>\\S*)\\s+(?P<b>\\S*\\s\\S*)\\s+(?P<c>\\d{1,})\\s+(?P<d>(?:[RSDTHCBIMPr ]?){1,5})\\s+(?P<e>\\S*\\s\\S*)\\s+(?P<f>\\S*\\s\\S*)$"
