    - name: get show 
      ios_command:
        commands:
          - "show run"
        timeout: "{{ set_timeout }}"
      register: output
    - set_fact:
        sh_run_config: "{{ output.stdout[0] |  parse_cli('ios_show_running_config_parser.yml') }}"  
    - copy: 
        content: "{{ sh_run_config | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_run_config.json

    - set_fact:
        sh_run_config_user: "{{ output.stdout[0] |  parse_cli('ios_show_running_config_username_parser.yml') |  json_query('config_users[].{username:username,privilege:privilege, secret_value:secret_value,fingerprint:fingerprint}')  }}"
    - copy: 
        content: "{{ sh_run_config_user | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_run_config_user.json

    - set_fact:
        sh_run_config_dhcp: "{{ output.stdout[0] |  parse_cli('ios_show_running_config_dhcp_parser.yml') }}"
    - copy: 
        content: "{{ sh_run_config_dhcp | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_run_config_dhcp.json
    - set_fact:
        sh_run_config_dhcp_ex: "{{ output.stdout[0] |  parse_cli('ios_show_running_config_dhcp_excluded_parser.yml') | json_query('ip_dhcp_excluded[].[range]')|flatten}}"
    - copy: 
        content: "{{ sh_run_config_dhcp_ex | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_run_config_dhcp_ex.json

    # - set_fact:
    #     crypto_pki_trustpoint: "{{ output.stdout[0] |  parse_cli('ios_show_running_config_crypto_pki_trustpoint_parser.yml') }}" 
    # - copy: 
    #     content: "{{ crypto_pki_trustpoint | to_nice_json }}"
    #     dest: /etc/ansible/files/{{hostname}}_crypto_pki_trustpoint.json

    # - set_fact:
    #     crypto_pki_cert: "{{ output.stdout[0] |  parse_cli('ios_show_running_config_crypto_pki_certificate_parser.yml') }}"     
    # - copy: 
    #     content: "{{ crypto_pki_cert | to_nice_json }}"
    #     dest: /etc/ansible/files/{{hostname}}_crypto_pki_cert.json

    - set_fact:
        sh_run_config_vlan: "{{ output.stdout[0] |  parse_cli('ios_show_running_config_vlan_parser.yml') }}"   
    - copy: 
        content: "{{ sh_run_config_vlan | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_run_config_vlan.json

    - set_fact:
        sh_run_config_interface: "{{ output.stdout[0] |  parse_cli('ios_show_running_config_interface_parser.yml') }}"
    - copy: 
        content: "{{ sh_run_config_interface | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_run_config_interface.json 
        
    - set_fact:
        sh_run_config_line: "{{ output.stdout[0] |  parse_cli('ios_show_running_config_line_parser.yml') }}" 
    - copy: 
        content: "{{ sh_run_config_line | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_run_config_line.json

    - name: get show interface status
      ios_command:
        commands:
          - "show interface status"
        timeout: "{{ set_timeout }}"
      register: output
      until: output.failed == false
      retries: 3
    - set_fact:
        sh_interface_status: "{{ output.stdout[0] | parse_cli('ios_show_interface_status_parser.yml') }}" 
    - copy: 
        content: "{{ sh_interface_status | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_interface_status.json

    - name: get show interface stats
      ios_command:
        commands:
          - "show interface stats"
        timeout: "{{ set_timeout }}"
      register: output
      until: output.failed == false
      retries: 3
    - set_fact:
        sh_interface_stats: "{{ output.stdout[0] | parse_cli('ios_show_interface_stats_parser.yml') }}"  
    - copy: 
        content: "{{sh_run_config_line | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_interface_stats.json

    - name: get show interface 
      ios_command:
        commands:
          - "show interface"
        timeout: "{{ set_timeout }}"
      register: output
    - set_fact:
        sh_interfaces: "{{ output.stdout[0] | parse_cli('ios_show_interface_parser.yml') }}"  
    - copy: 
        content: "{{ sh_interfaces | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_interfaces.json

    - name: get show interface summary
      ios_command:
        commands:
          - "show interface summary"
        timeout: "{{ set_timeout }}"
      register: output
    - set_fact:
        sh_interface_summary: "{{ output.stdout[0] | parse_cli('ios_show_interface_summary_parser.yml') }}"  
    - copy: 
        content: "{{ sh_interface_summary | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_interface_summary.json

    - name: get show vlan-switch
      ios_command:
        commands:
          - "show vlan-switch"
        timeout: "{{ set_timeout }}"
      register: network_cli  
    - set_fact:  
        sh_vlan_switch: "{{ network_cli.stdout[0] | parse_cli('ios_show_vlan_switch_parser.yml') }}"
    - copy: 
        content: "{{ sh_vlan_switch | to_nice_json }}"
        dest: /etc/ansible/files/{{hostname}}_sh_vlan_switch.json
