# - set_fact:    
#     not_allowed_id: "{{ (all_id2| difference(((intended_cfg_main_int_sw_port[outer_item].allowed +\",\"+ default_vlan) | dash2inrange_int)) | inrange_int2dash).split(',') | mybatch(4) | list  }}"
#     allowed_id: "{{ (((intended_cfg_main_int_sw_port[outer_item].allowed +\",\"+ default_vlan) | dash2inrange_int |unique) | inrange_int2dash).split(',') | mybatch(4) |list}}" 
#     ff: "{{intended_cfg_main_vlan[0].id| int}}"
#     gg: "{{(intended_cfg_main_int_sw_port[outer_item].allowed | dash2inrange_int)}}"
#     hh: "{{intended_cfg_main_vlan[0].id|int in (intended_cfg_main_int_sw_port[outer_item].allowed | dash2inrange_int)}}"
  
    # allowed_id2: "{{ (intended_cfg_main_int_sw_port[outer_item].allowed +\",\"+ default_vlan) | dash2inrange_int | json_query(\"[?contains(to_string(@),'\"+intended_cfg_main_vlan[0].id+\"')].@\") }}" 
    # '\"+intended_cfg_main_int_sw_port[outer_item].name+\"'
    # (running_cfg_main_int_sw_port | to_json | from_json | json_query('[?name == `FastEthernet1/11`].trunk_enabled')|default())+\"
    # asdas: "{{running_cfg_main_int_sw_port |to_json |from_json | json_query(\"[?name == '\"+intended_cfg_main_int_sw_port[outer_item].name+\"'].trunk_enabled\")|join('')}}"
    # asdas2: "{{ sh_interfaces |to_json |from_json | json_query('[?contains(name, `vlan`)] | [?ipv4 != null].name')| join(',')| replace('vlan ','')   }}"
# - set_fact:
#     asdfwef: "{{intended_cfg_main_int_sw_port[outer_item].name}}"
# - set_fact:
#     asdfwe234f: "{{running_cfg_main_int_sw_port}}"
# - set_fact:
#     asdfw234f: "{{intended_cfg_main_int_sw_port[outer_item].allowed}}"
# - set_fact:
#     asdfw234fasd: "{{intended_cfg_main_vlan[0].id}}"

- set_fact:
    # found: "{{ (intended_cfg_main_vlan[0].id|int) in ((intended_cfg_main_int_sw_port[outer_item].allowed +\",\"+ default_vlan) |dash2inrange_int |unique)}}"
    identic: "{{ (running_cfg_main_int_sw_port |to_json |from_json | json_query(\"[?name == '\"+intended_cfg_main_int_sw_port[outer_item].name+\"'].trunk_enabled\")|join('') |dash2inrange_int |unique |inrange_int2dash) == ((intended_cfg_main_int_sw_port[outer_item].allowed| replace('all', all_id) +\",\"+ intended_cfg_main_vlan[0].id +\",\"+ default_vlan) |dash2inrange_int |unique |inrange_int2dash) }}"
    check: "{{intended_cfg_main_int_sw_port[outer_item].name}}"
- block:
    - set_fact:     
        # not_allowed_id: "{{ (all_id2| difference((intended_cfg_main_int_sw_port[outer_item].allowed +\",\"+ default_vlan )| dash2inrange_int |unique) | inrange_int2dash).split(',') | mybatch(24) | list  }}"
        # allowed_id: "{{ (((intended_cfg_main_int_sw_port[outer_item].allowed +\",\"+ default_vlan  ) |dash2inrange_int |unique) |inrange_int2dash).split(',') |mybatch(24) |list}}"
        # allowed_id2: "{{ ((intended_cfg_main_int_sw_port[outer_item].allowed +\",\"+ default_vlan) |dash2inrange_int |unique |inrange_int2dash).split(',') |mybatch(24) |list}}"
        # allowed_id3: "{{ ((intended_cfg_main_int_sw_port[outer_item].allowed +\",\"+ default_vlan +\",\"+ running_cfg_main_int_sw_port[10].trunk_enabled) |dash2inrange_int |unique |inrange_int2dash).split(',') |mybatch(24) |list}}"
        # not_allowed_id: "{{ (all_id | dash2inrange_int| difference((intended_cfg_main_int_sw_port[outer_item].allowed| replace('all', all_id) +\",\"+ default_vlan +\",\"+ running_cfg_main_int_sw_port |to_json |from_json | json_query(\"[?name == '\"+intended_cfg_main_int_sw_port[outer_item].name+\"'].trunk_enabled\")|join('') )| dash2inrange_int |unique) | inrange_int2dash).split(',') | mybatch(24) | list  }}"
        not_allowed_id: "{{ (all_id | dash2inrange_int| difference((intended_cfg_main_int_sw_port[outer_item].allowed| replace('all', all_id) +\",\"+ intended_cfg_main_vlan[0].id +\",\"+ default_vlan +\",\"+ sh_interfaces |to_json |from_json | json_query('[?contains(name, `vlan`)] | [?ipv4 != null].name')| join(',')| replace('vlan ','') )| dash2inrange_int |unique) | inrange_int2dash).split(',') | mybatch(24) | list  }}"
        allowed_id: "{{ ((intended_cfg_main_int_sw_port[outer_item].allowed| replace('all', all_id) +\",\"+ intended_cfg_main_vlan[0].id +\",\"+ default_vlan +\",\"+ sh_interfaces |to_json |from_json | json_query('[?contains(name, `vlan`)] | [?ipv4 != null].name')| join(',')| replace('vlan ','') ) |dash2inrange_int |unique |inrange_int2dash).split(',') |mybatch(24) |list}}"
        
    - set_fact: 
        tmp_n_allowed: "{{tmp_n_allowed | default([]) + [] | zip_longest(not_allowed_id, fillvalue=intended_cfg_main_int_sw_port[outer_item].name) | list }}"
        tmp_allowed: "{{tmp_allowed | default([]) + [] | zip_longest(allowed_id, fillvalue=intended_cfg_main_int_sw_port[outer_item].name) | list }}"
  when: not identic
  delegate_to: localhost
