# for  VLAN MGMNT  
 

# # how to find vlan in allowed vlan of switchport trunk
# # ex: find vlan 1097 in 1094-1098,1957,3101-3102,3104,3151-3152,3152,3154     
# - set_fact:
#     find: "{{mgmnt.new_vlan[0].id}}"
#     it: "{{mgmnt.sw_port[0].allowed}}"
# - set_fact:
#     split1: "{{it.split(',') | json_query('[?contains(@, `-`) == `true`]')}}"
#     split2: "{{it.split(',') | json_query('[?contains(@, `-`) == `false`]')}}"
# - set_fact:
#     items: "{{range(item.split('-').0|int,item.split('-').1|int+1) | list}}"
#   loop: "{{split1}}"
#   register: split1
# - set_fact:
#     it: "{{ ([split1 | json_query('results[:].ansible_facts.items'),split2] | flatten | join(',')).split(',')  | unique | sort}}"
# - set_fact:
#     exist: "{{find in it}}"

# # how to find, int vlan is the vlan mgmnt ?
# - set_fact:
#     ansible_host: "{{ item.ip }}"
#   loop: "{{ mgmnt.int_vlan }}"
#   when: mgmnt.new_vlan[0].id in item.name  
#   failed_when: mgmnt.new_vlan[0].id not in item.name  # lanjutan kitka fail belum ada???!!
# # end of variable from roles variable_inspect
- pause:
    prompt: "VAR INSPECT ?"

- include_vars: ../network_vlan/vars/vlan_db.yml
- include_vars: 
    file: ../network_vlan/vars/vlan_db_old.yml
    name: old
- include_vars: 
    file: ../../host_vars/old_sw_ku3_a1.yml
    name: old2
- set_fact:
    old_vlan       : "{{ old.vlan_db    | json_query('[?main==`true`].{name:name, id:vlan_id}')    | mandatory }}"
    new_vlan       : "{{ vlan_db        | json_query('[?main==`true`].{name:name, id:vlan_id}')    | mandatory }}"
    run_vlan       : "{{ sh_vlan_switch | json_query('vlans[?status==`active`].{id:id,name:name,ports:ports}') }}"

    new_int_vlan   : "{{ interface      | json_query('[?main==`true`].{name:name,ip:ip,prefix:prefix}') | mandatory }}"
    old_int_vlan   : "{{ old2.interface | json_query('[?main==`true`].{name:name,ip:ip,prefix:prefix}') | mandatory }}"
    run_int_vlan   : "{{ sh_interfaces | to_json | from_json | json_query(\"[?ipv4 == '\" + ansible_host + \"'].{name:name,ip:ipv4,lineprostate:link_protocol_state,prefix:prefix,operstatus:operstatus}\")  }}"
    myrunningmainip: "{{ansible_host}}"
    myrunningmainvlan: "{{ sh_interfaces | to_json | from_json | json_query(\"[?ipv4 == '\" + ansible_host + \"'].name | [0]\") | replace('vlan ','')}}"
- set_fact: 
    myrunningmainint: "{{ sh_interface_switchport | json_query(\"[?trunk_active!=`none`].{trunk_active:trunk_active.to_array(@)[].to_string(@)|[?contains(@, '\" + myrunningmainvlan + \"') == `true`],name:name}| [?trunk_active].name \") }}"
- pause:
    prompt: ""
- set_fact:
    
    
    new_int_sw_port: "{{ interface      | json_query('[?allowed!=[]].{name:name,mode:mode,allowed:allowed}')  }}"
    old_int_sw_port: "{{ old2.interface | json_query('[?allowed!=[]].{name:name,mode:mode,allowed:allowed}')  }}"
    run_int_sw_port: "{{ sh_interface_switchport | json_query('[?trunk_active!=`none`].{name:name,mode_op:mode_op,mode_admin:mode_admin,trunk_enabled:trunk_enabled,trunk_active:trunk_active}   ') | replace('ALL','1-4094') }}"

- pause:
    prompt: ""
- set_fact:
    a: "{{new_int_sw_port[0].allowed.split(',') | json_query('[?contains(@, `-`) == `true`]')}}"
    b: "{{new_int_sw_port[0].allowed.split(',') | json_query('[?contains(@, `-`) == `false`]')}}"
    c: "{{old_int_sw_port[0].allowed.split(',') | json_query('[?contains(@, `-`) == `true`]')}}"
    d: "{{old_int_sw_port[0].allowed.split(',') | json_query('[?contains(@, `-`) == `false`]')}}"
    e: "{{run_int_sw_port[0].trunk_enabled.split(',') | json_query('[?contains(@, `-`) == `true`]')}}"
    f: "{{run_int_sw_port[0].trunk_enabled.split(',') | json_query('[?contains(@, `-`) == `false`]')}}"
     


# - pause:
#     prompt: "OK?"

- set_fact:
    covi: "{{ item.id not in (old_vlan | json_query('[].id')) }}"     # i for id
    covn: "{{ item.name not in (old_vlan | json_query('[].name')) }}" # n for name
    ov: "{{ item }}"
  loop:  "{{ run_vlan }}"
  loop_control :
    label: "{{item.id}}"
  when: item.id in (old_vlan | json_query('[].id'))
- set_fact:
    cnvi: "{{ item.id not in (new_vlan | json_query('[].id')) }}"     # i for id
    cnvn: "{{ item.name not in (new_vlan | json_query('[].name')) }}" # n for name
    nv: "{{ item }}"
  loop:  "{{ run_vlan }}"
  loop_control :
    label: "{{item.id}}"
  when: item.id in (new_vlan | json_query('[].id'))


- set_fact:
    coivip  : "{{ item.ip not in (old_int_vlan | json_query('[].ip')) }}"
    coivpfx : "{{ item.prefix not in (old_int_vlan | json_query('[].prefix')) }}"
  loop: "{{run_int_vlan}}"
  loop_control :
    label: "{{item.name}}"
  when: item.name in (old_int_vlan | json_query('[].name'))
- set_fact:
    cnivip  : "{{ item.ip not in (new_int_vlan | json_query('[].ip')) }}"
    cnivpfx : "{{ item.prefix not in (new_int_vlan | json_query('[].prefix')) }}"
  loop: "{{run_int_vlan}}"
  loop_control :
    label: "{{item.name}}"
  when: item.name in (new_int_vlan | json_query('[].name'))
- set_fact:
    cnswport: 
- debug:

- pause:
    prompt: "????"


# - pause:
#     prompt: "OK?"


            # - set_fact:
            #     find: "{{mgmnt.new_vlan[0].id}}"
            #     it: "{{mgmnt.sw_port[0].allowed}}"
            # - set_fact:
            #     split1: "{{it.split(',') | json_query('[?contains(@, `-`) == `true`]')}}"
            #     split2: "{{it.split(',') | json_query('[?contains(@, `-`) == `false`]')}}"
            # - set_fact:
            #     items: "{{range(item.split('-').0|int,item.split('-').1|int+1) | list}}"
            #   loop: "{{split1}}"
            #   register: split1
            # - set_fact:
            #     it: "{{ ([split1 | json_query('results[:].ansible_facts.items'),split2] | flatten | join(',')).split(',')  | unique | sort}}"
            # - set_fact:
            #     exist: "{{find in it}}"
            # - set_fact:
            #     mgmnt:
            #       changes:
            #         vlan_id   : "{{cnvi}}" # true if vlan id is changed (is it declared or not yet) through current 
            #         vlan_name : "{{cnvn}}" # true if vlan name is changed
            #         ip        : "{{cnivip}}" # true if ip addr is changed
            #         prefix    : "{{cnivpfx}}" # true if prefix is changed
            #         int_phy   : false # true if int(Se/F/Ge/Eth) is changed
            #         sw_port   : true # true if allowed vlan list is changed
            #         exist     : true # # true if vlan id found in allowed vlan list of switchport trunk
            #       new_vlan      : "{{new_vlan}}"
            #       old_vlan      : "{{old_vlan}}"
            #       int_vlan      : "{{new_int_vlan}}"
            #       old_int_vlan  : "{{old_int_vlan}}"
            #       int_phy       : "{{new_int_sw_port}}"
            #       sw_port       : "{{old_int_sw_port}}"
            # - set_fact:
            #     vlan_mgmnt_changes_found: true
            # - include_vars: ../network_vlan/vars/vlan_db.yml
            # - set_fact:
            #     vlan_mgmnt: "{{vlan_db | json_query('[?mandatory==`true`].{name:name,vlan_id:vlan_id}') | mandatory }}"
            # - set_fact:
            #     vlan_mgmn_count: "{{vlan_db | json_query('[?mandatory==`true`].{name:name,vlan_id:vlan_id}') |length}}"
            # - set_fact:
            #     vlan_mgmnt: "{{vlan_db | json_query('[?mandatory==`true`].{name:name,vlan_id:vlan_id}') | mandatory }}"
            #   when: vlan_mgmn_count | int > 0
            # - block:
            #     - debug:
            #         msg: "vlan mgmn amount is zero or exceed limit , using vlan_db_old instead"
            #       when: vlan_mgmnt is not defined
            #       failed_when: vlan_mgmnt is not defined
            #   rescue:
            #     - include_vars:
            #         file:  ../network_vlan/vars/vlan_db_old.yml
            #         name: vlan_db_old
            #     - set_fact:
            #         vlan_mgmnt: "{{vlan_db_old.vlan_db | json_query('[?mandatory==`true`].{name:name,vlan_id:vlan_id}') | mandatory }}"
            # - debug:
            #     var: vlan_mgmnt