- block:
    - include_vars: ../network_vlan/vars/vlan_db.yml
    - include_vars: 
        file: ../network_vlan/vars/vlan_db_old.yml
        name: old
    - include_vars: 
        file: "../../host_vars/old_{{inventory_hostname}}.yml"
        name: old2
    - set_fact:
        intended_cfg_main_vlan         : "{{ vlan_db        | json_query('[?main==`true`].{name:name, id:vlan_id}')    | mandatory }}"
        old_saved_cfg_main_vlan        : "{{ old.vlan_db    | json_query('[?main==`true`].{name:name, id:vlan_id}')    | mandatory }}"
        # running_cfg_main_vlan          : "{{ sh_vlan_switch | json_query('vlans[?status==`active`].{id:id,name:name,ports:ports}') }}"
        # running_cfg_main_vlan2         : "{{ (sh_interfaces  | to_json | from_json | json_query(\"[?ipv4 == '\"+ansible_host+\"'].name\") | join(',') | replace('vlan ',''))  }}"
        running_cfg_main_vlan        : "{{ sh_vlan_switch | to_json | from_json | json_query(\"vlans[?id== '\"+(sh_interfaces  | to_json | from_json | json_query(\"[?ipv4 == '\"+ansible_host+\"'].name\") | join(',') | replace('vlan ',''))+\"'].{id:id,name:name,ports:ports}\")  }}"
    - set_fact:
        intended_cfg_main_vlan         : "{%if intended_cfg_main_vlan == [] %}{{old_saved_cfg_main_vlan}}{%else%}{{intended_cfg_main_vlan}}{%endif%}"  # nilai digantikan apabila intended_cfg_main_vlan lupa belum di deklarasi/notfound
    - set_fact:
        intended_cfg_main_int_vlan     : "{{ interface      | to_json | from_json | json_query(\"[?contains(name.to_string(@),'\"+intended_cfg_main_vlan[0].id+\"')]\") | mandatory }}"
        old_saved_cfg_main_int_vlan    : "{{ old2.interface | to_json | from_json | json_query(\"[?contains(name.to_string(@),'\"+old_saved_cfg_main_vlan[0].id+\"')]\") | mandatory }}"
        running_cfg_main_int_vlan      : "{{ sh_interfaces  | to_json | from_json | json_query(\"[?ipv4 == '\"+ansible_host+\"'].{name:name,ip:ipv4,lineprostate:link_protocol_state,prefix:prefix,operstatus:operstatus}\")  }}" 
    - set_fact:
        intended_cfg_main_int_vlan     : "{%if intended_cfg_main_int_vlan == [] %}{{old_saved_cfg_main_int_vlan}}{%else%}{{intended_cfg_main_int_vlan}}{%endif%}" # nilai digantikan apabila intended_cfg_main_int_vlan lupa belum di deklarasi/notfound
    - set_fact:
        intended_cfg_main_int_sw_port  : "{{ interface      | json_query('[?allowed!=[]].{name:name,mode:mode,allowed:allowed}')  }}"
        old_saved_cfg_main_int_sw_port : "{{ old2.interface | json_query('[?allowed!=[]].{name:name,mode:mode,allowed:allowed}')  }}"        
        running_cfg_main_int_sw_port   : "{{ sh_interface_switchport | json_query('[?trunk_active!=`none`].{name:name,mode_op:mode_op, mode_admin:mode_admin,trunk_enabled:trunk_enabled,trunk_active:trunk_active}   ') | replace('ALL','1-4094') }}"   
        running_cfg_main_int_sw_port2:  "{{ (sh_interface_switchport| to_json | from_json | json_query(\"[?contains(trunk_active.to_string(@),'\"+intended_cfg_main_vlan[0].id+\"')]\"))  | replace('ALL','1-4094')  }}"
        interfaces_have_neighbors: "{{ (sh_cdp_nei.show_nei | to_json | from_json | json_query(\"[?contains(device_id.to_string(@),'\"+sh_run_config[0].ip_domain_name+\"')].local_interface\"))  | replace(' ','') }}" #find neighbors with in our domain name,  then it is means the port is essential and shold only use method add all then remove the unnecessary . Instead of method remove all then add the necessary


        myrunning_mgmt_ip              : "{{ ansible_host }}"                                                                              
        myrunning_mgmt_id              : "{{ sh_interfaces | to_json | from_json | json_query(\"[?ipv4 == '\" + ansible_host + \"'].name | [0]\") | replace('vlan ','')}}"
        
    - set_fact:
        mgmnt:
          changes:
            vlan_id   : "{{         intended_cfg_main_vlan[0].id != running_cfg_main_vlan[0].id         }}" 
            vlan_name : "{{       intended_cfg_main_vlan[0].name != running_cfg_main_vlan[0].name       }}" 
            ip        : "{{ intended_cfg_main_int_vlan[0].ip | ipv4('address') != running_cfg_main_int_vlan[0].ip     }}" 
            prefix    : "{{ intended_cfg_main_int_vlan[0].ip | ipv4('prefix') != running_cfg_main_int_vlan[0].prefix }}" 
        variable_inspect_was_done: yes
    # - pause:
    #     prompt: ""
    - name: helper loop
      include_tasks: "{{role_path}}/tasks/helper_loop.yml"
      loop: "{{ range(0|int,intended_cfg_main_int_sw_port|length|int)|list}}"
      loop_control:
        loop_var: outer_item
      when: intended_cfg_main_int_sw_port[outer_item].name in interfaces_have_neighbors 
  delegate_to: localhost