
# sh int status
# Port    Name               Status       Vlan       Duplex Speed Type
# Fa1/0                      notconnect   901          auto    auto 10/100BaseTX
# Fa1/1                      notconnect   901          auto    auto 10/100BaseTX
# Fa1/2                      connected    901          full     100 10/100BaseTX
# Fa1/3                      connected    901          full     100 10/100BaseTX
# Fa1/4                      connected    901          full     100 10/100BaseTX
# Fa1/5                      connected    1            full     100 10/100BaseTX
# Fa1/6                      connected    1            full     100 10/100BaseTX
# Fa1/7                      connected    1            full     100 10/100BaseTX
# Fa1/8                      connected    1            full     100 10/100BaseTX
# Fa1/9                      connected    1            full     100 10/100BaseTX
# Fa1/10                     connected    trunk        full     100 10/100BaseTX
# Fa1/11                     connected    trunk        full     100 10/100BaseTX
# Fa1/12                     connected    trunk        full     100 10/100BaseTX
# Fa1/13                     connected    trunk        full     100 10/100BaseTX
# Fa1/14                     connected    trunk        full     100 10/100BaseTX
# Fa1/15                     connected    trunk        full     100 10/100BaseTX

vars:
  status:
    port  : "{{ item.ports }}"
    vlan  : "{{ item.vlan }}"
    status: "{{ item.status }}"
    deplex: "{{ item.duplex }}"
    speed : "{{ item.speed }}"
    type  : "{{ item.type }}"
  
keys:
  interface_status:
    value: "{{ status }}"
    items: "^(?P<ports>\\w+/\\d+)\\s+(?P<status>\\w+)\\s+(?P<vlan>\\w+(|,\\w+))\\s+(?P<duplex>[a-zA-Z-]+)\\s+(?P<speed>\\w+)\\s+(?P<type>\\w+/\\w+)?"  
    #(?P<ports>\w+/\d+)\s+(?P<status>\w+)\s+(?P<vlan>\w+)\s+(?P<duplex>\w+)\s+(?P<speed>\w+)\s+(?P<type>\w+/\w+)