
vars:
  vlan:
    id: "{{ item.id }}"
    name: "{{ item.name }}"
    status: "{{ item.status }}"
    ports: "{{ (item.ports|replace('Gi', 'GigabitEthernet') | replace('Po','PortChannel')).split(', ') }}"


keys:
  vlans:
    value: "{{ vlan }}"
    items: "^(?P<id>\\d+)\\s+(?P<name>\\S+)\\s+(?P<status>[a-z/]{4,})($|\\s{4}(?P<ports>.*/\\d*$))?"
    
