
vars:
  config:
    cur_conf_size: "{{ item[0].cur_conf_size }}"
    version: "{{ item[1].version }}"
    timestamps_log: "{{ item[2].timestamps_log }}"
    timestamps_debug: "{{ item[3].timestamps_debug }}"
    pass_encrypt_set: "{{ item[4].pass_encrypt_set }}"
    hostname: "{{ item[5].hostname }}"
    ena_secret_value: "{{ item[6].ena_secret_value }}"
    ena_secret_fingerprint: "{{ item[6].ena_secret_fingerprint }}"
    clock_timezone: "{{ item[7].clock_timezone }}"
    ip_dhcp_snooping_vlan: "{{ item[8].ip_dhcp_snooping_vlan }}"
    vtp_mode: "{{ item[9].vtp_mode }}"
    spanning_tree_mode: "{{ item[10].spanning_tree_mode }}"
    spanning_tree_extend: "{{ item[11].spanning_tree_extend }}"
    spanning_vlan_status: "{{ item[12].spanning_vlan_status }}"
    spanning_tree_vlan: "{{ item[12].spanning_tree_vlan }}"
    viap: "{{ item[13].viap }}"
    ip_http_server_stats: "{{ item[14].ip_http_server_stats }}"
    ip_https_server_stats: "{{ item[15].ip_https_server_stats }}"
    log_severity_lvl: "{{ item[16].log_severity_lvl }}"
    log_facility: "{{ item[17].log_facility }}"
    log_hostname: "{{ item[18].log_hostname }}"
    snmp_srv_community: "{{ item[19].snmp_srv_community }}"
    snmp_srv_location: "{{ item[20].snmp_srv_location }}"
    snmp_srv_contact: "{{ item[21].snmp_srv_contact }}"
    ntp_server_addr: "{{ item[22].ntp_server_addr }}"
    ip_def_gw: "{{ item[23].ip_def_gw }}"




keys: 
  configs:
    value: "{{ config }}"
    start_block: "^Building.*" 
    end_block: ".*transport input ssh$" #".*end$"
    items:
      - "(Build\\w+).*\\n*(\\n|Current configuration \\W* )(?P<cur_conf_size>\\d*)"
      - "version (?P<version>.*)"
      - "service timestamps log (?P<timestamps_log>.*)"
      - "service timestamps debug (?P<timestamps_debug>.*)"
      - "(?P<pass_encrypt_set>.*)service password-encryption"
      - "hostname (?P<hostname>.*)"
      - "enable secret (?P<ena_secret_value>\\d) (?P<ena_secret_fingerprint>.*)"
      - "clock timezone (?P<clock_timezone>.*)"
      - "ip dhcp snooping vlan (?P<ip_dhcp_snooping_vlan>.*)"
      - "vtp mode (?P<vtp_mode>.*)"
      - "spanning-tree mode (?P<spanning_tree_mode>.*)"
      - "spanning-tree extend (?P<spanning_tree_extend>.*)"
      - "(?P<spanning_vlan_status>no |)spanning-tree vlan (?P<spanning_tree_vlan>.*\\d)"
      - "vlan internal allocation policy (?P<viap>.*)"
      - "(?P<ip_http_server_stats>no|) ip http server"
      - "(?P<ip_https_server_stats>no|) ip http secure-server"
      - "logging trap (?P<log_severity_lvl>.*)"
      - "logging facility (?P<log_facility>.*)"
      - "logging host (?P<log_hostname>.*)"
      - "snmp-server community (?P<snmp_srv_community>.*)"
      - "snmp-server location (?P<snmp_srv_location>.*)"
      - "snmp-server contact (?P<snmp_srv_contact>.*)"
      - "ntp server (?P<ntp_server_addr>.*)"
      - "ip default-gateway (?P<ip_def_gw>.*)"
      
##    
  # user:
  #   name: "{{ item[0].name }}"
  #   link_protocol_state: "{{ item[0].oper }}"
  #   admin_state: "{{ item[5].admin }}"
  #   ipv4: "{{ item[1].match[0] }}"
  #   mtu: "{{ item[2].match[0] }}"
  #   port_mode: "{{ item[3].match[0] }}"
  # pool:
  #   name: "{{ item[0].name }}"
  #   link_protocol_state: "{{ item[0].oper }}"
  #   admin_state: "{{ item[5].admin }}"
  #   ipv4: "{{ item[1].match[0] }}"
  #   mtu: "{{ item[2].match[0] }}"
  #   port_mode: "{{ item[3].match[0] }}"
  # crypto_trustpoint:
  #   name: "{{ item[0].name }}"
  # crypto_cert:
  #   name: "{{ item[0].name }}"
  # vlans:
  #   name: "{{ item[0].name }}"
  # interfaces:
  #   name: "{{ item[0].name }}"
  # lines:
  #   name: "{{ item[0].name }}"


#       - "(?P<name>\\w+/\\d+|Vlan\\w+) is(?P<aa>\\s?"
#   config_dhcp_pools:
#     value: "{{ pool }}"
#     start_block: "\\w{0,20}?(Serial|Ethernet)\\d[/]\\d+"
#     end_block: ".+interface reset"
#     items:
#       - "(?P<name>\\w+/\\d+|Vlan\\w+) is(?P<aa>\\s?"
#   config_crypto_trustpoint:
#     value: "{{ crypto_trustpoint }}"
#     start_block: "\\w{0,20}?(Serial|Ethernet)\\d[/]\\d+"
#     end_block: ".+interface reset"
#     items:
#       - "(?P<name>\\w+/\\d+|Vlan\\w+) is(?P<aa>\\s?"
#   config_crypto_certs:
#     value: "{{ crypto_cert }}"
#     start_block: "\\w{0,20}?(Serial|Ethernet)\\d[/]\\d+"
#     end_block: ".+interface reset"
#     items:
#       - "(?P<name>\\w+/\\d+|Vlan\\w+) is(?P<aa>\\s?"
#   config_vlans:
#     value: "{{ vlans }}"
#     start_block: "\\w{0,20}?(Serial|Ethernet)\\d[/]\\d+"
#     end_block: ".+interface reset"
#     items:
#       - "(?P<name>\\w+/\\d+|Vlan\\w+) is(?P<aa>\\s?"
#   config_interfaces:
#     value: "{{ interfaces }}"
#     start_block: "\\w{0,20}?(Serial|Ethernet)\\d[/]\\d+"
#     end_block: ".+interface reset"
#     items:
#       - "(?P<name>\\w+/\\d+|Vlan\\w+) is(?P<aa>\\s?"
#   config_lines:
#     value: "{{ lines }}"
#     start_block: "\\w{0,20}?(Serial|Ethernet)\\d[/]\\d+"
#     end_block: ".+interface reset"
#     items:
#       - "(?P<name>\\w+/\\d+|Vlan\\w+) is(?P<aa>\\s?"




# # per line
# -(?P<ports>Build\w+).*\n*(\n|Current configuration : )(?P<cur_conf_size>\d*)
# -version (?P<version>.*)
# -service timestamps log (?P<timestamps_log>.*)
# -service timestamps debug (?P<timestamps_debug>.*)
# -(?P<pass_encrypt_set>.*)service password-encryption
# -hostname (?P<hostname>.*)
# -enable secret (?P<value>\d) (?P<fingerprint>.*)
# -clock timezone (?P<clock_timezone>.*)
# -ip dhcp snooping vlan (?P<ip_dhcp_snooping_vlan>.*)
# -vtp mode (?P<vtp_mode>.*)
# -spanning-tree mode (?P<spanning_tree_mode>.*)
# -spanning-tree extend (?P<spanning_tree_extend>.*)
# -(?P<spanning_vlan_status>no |)spanning-tree vlan (?P<spanning_tree_extend>.*\d)
# -vlan internal allocation policy (?P<viap>.*)
# -(?P<ip_http_server_stats>no|) ip http serverv
# -(?P<ip_http_server_stats>no|) ip http secure-server
# -logging trap (?P<log_severity_lvl>.*)
# -logging facility (?P<log_facility>.*)
# -logging host (?P<log_hostname>.*)
# -snmp-server community (?P<snmp_srv_community>.*)
# -snmp-server location (?P<snmp_srv_location>.*)
# -snmp-server contact (?P<snmp_srv_contact>.*)

# #block
# -username (?P<username>\w*)(| privilege (?P<priv>\w*)) secret (?P<finger_value>\d*) (?P<fingerprint_value>.*)

# -ip dhcp excluded-address (?P<var1>.*)
# -ip dhcp pool (?P<var2>.*)
# - network (?P<clock_timezone>.*)
# - (\n dns-server (?P<dns_server3>.*))
# - (\n default-router (?P<default_router>.*))
# - (\n domain-name (?P<domain_name>.*))
# - (\n lease (?P<leaseday>\d*) (?P<leasehour>\d*))

# -crypto pki trustpoint (?P<name_cryto_pki_truspoint>.*)
# -enrollment (?P<enrollment_cryto_pki_truspoint>.*)
# -subject-name cn=(?P<cn>.*)
# -rsakeypair (?P<rsakeypair_name>.*)

# -crypto pki certificate chain (?P<cpcc_name>.*)
# -certificate (?P<cert_name>[a-zA-Z-]*) (?P<value>\d*)
# - (?P<cert_name>( [0-9A-F]{8}).*)


# -vlan (?P<vlan_id>\d*)\n
# -vlan (?P<vlan_id>.*)
# -\sname (?P<vlan_name>.*)
# -\sdescription (?P<vlan_desc>.*)

# -interface (?P<int_name>Serial.*|\w*Ethernet.*|Vlan.*)
# -ip address (?P<ip_addr>\d*.\d*.\d*.\d*) (?P<subnet>\d*.\d*.\d*.\d*)
# -(?P<ip_route_cache_stats>\sno |\s)ip route-cache( (?P<ip_route_cache_value>).*|)
# -switchport (?P<mode>.*) (vlan add |vlan )(?P<vlan_id>[0-9,]*)
# -spanning-tree bpduguard (?P<st_bpduguard>.*)


# -line (?P<line_type>\w*)\s*(?P<line_first_number>\d*)\s*(?P<line_last_number>\d*)
# -login (?P<login_opt>\w*)
# -transport input (?P<transport_ingoing_protocol>\w*)
# -transport output (?P<transport_outgoing_protocol>\w*)
# -timeout login response (?P<timout_line>\w*)