
# IOS Show Interface Parser

# Command:
#   - show interface [iface_name] (Single Interface listing)
#   - show interface ( Multiple interface listing)

# Example Command Output:
# ----------------------
# Serial0/3 is administratively down, line protocol is down
#   Hardware is GT96K Serial
#   MTU 1500 bytes, BW 1544 Kbit/sec, DLY 20000 usec,
#      reliability 255/255, txload 1/255, rxload 1/255
#   Encapsulation HDLC, loopback not set
#   Keepalive set (10 sec)
#   CRC checking enabled
#   Last input never, output never, output hang never
#   Last clearing of "show interface" counters never
#   Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0
#   Queueing strategy: weighted fair
#   Output queue: 0/1000/64/0 (size/max total/threshold/drops)
#      Conversations  0/0/256 (active/max active/max total)
#      Reserved Conversations 0/0 (allocated/max allocated)
#      Available Bandwidth 1158 kilobits/sec
#   5 minute input rate 0 bits/sec, 0 packets/sec
#   5 minute output rate 0 bits/sec, 0 packets/sec
#      0 packets input, 0 bytes, 0 no buffer
#      Received 0 broadcasts, 0 runts, 0 giants, 0 throttles
#      0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored, 0 abort
#      0 packets output, 0 bytes, 0 underruns
#      0 output errors, 0 collisions, 7 interface resets
#      0 output buffer failures, 0 output buffers swapped out
#      0 carrier transitions
#      DCD=up  DSR=up  DTR=up  RTS=up  CTS=up
# FastEthernet1/0 is up, line protocol is down
#   Hardware is Fast Ethernet, address is c204.299c.f100 (bia c204.299c.f100)
#   MTU 1500 bytes, BW 100000 Kbit/sec, DLY 100 usec,
#      reliability 255/255, txload 1/255, rxload 1/255
#   Encapsulation ARPA, loopback not set
#   Keepalive set (10 sec)
#   Auto-duplex, Auto-speed
#   ARP type: ARPA, ARP Timeout 04:00:00
#   Last input never, output never, output hang never
#   Last clearing of "show interface" counters never
#   Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0
#   Queueing strategy: fifo
#   Output queue: 0/40 (size/max)
#   5 minute input rate 0 bits/sec, 0 packets/sec
#   5 minute output rate 0 bits/sec, 0 packets/sec
#      0 packets input, 0 bytes, 0 no buffer
#      Received 0 broadcasts, 0 runts, 0 giants, 0 throttles
#      0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
#      0 input packets with dribble condition detected
#      0 packets output, 0 bytes, 0 underruns
#      0 output errors, 0 collisions, 2 interface resets
#      0 babbles, 0 late collision, 0 deferred
#      0 lost carrier, 0 no carrier
#      0 output buffer failures, 0 output buffers swapped out
# Vlan1097 is up, line protocol is up
#   Hardware is EtherSVI, address is c204.1f30.0000 (bia c204.1f30.0000)
#   Internet address is 10.240.192.4/16
#   MTU 1500 bytes, BW 100000 Kbit/sec, DLY 100 usec,
#      reliability 255/255, txload 1/255, rxload 1/255
#   Encapsulation ARPA, loopback not set
#   ARP type: ARPA, ARP Timeout 04:00:00
#   Last input 00:00:00, output never, output hang never
#   Last clearing of "show interface" counters never
#   Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0
#   Queueing strategy: fifo
#   Output queue: 0/40 (size/max)
#   5 minute input rate 3000 bits/sec, 5 packets/sec
#   5 minute output rate 3000 bits/sec, 3 packets/sec
#      16788 packets input, 1075288 bytes, 0 no buffer
#      Received 2585 broadcasts, 0 runts, 0 giants, 0 throttles
#      0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
#      14029 packets output, 2262107 bytes, 0 underruns
#      0 output errors, 1 interface resets
#      0 output buffer failures, 0 output buffers swapped out

#
# Example Playbook
# -----------------
# -hosts: localhost
#  connection: local
#  vars:
#    iface_parse_path: /path/to/parsers/ios_show_interface_parser.yml
#  tasks:
#     - name: Get Interface information
#       ios_command:
#         commands: show interface FastEthernet1/2
#       register: output
#
#     - name: Parse Interface Output
#       set_fact:
#         ios_interface: "{{ output.stdout[0] | parse_cli(iface_parser_path)}}"

# Schema Output
# -------------


vars:
  interface:
    name                : "{{ item[0].name | replace('Vlan','vlan ')}}"
    operstatus          : "{{ item[0].oper }}"
    ipv4                : "{{ item[1].ipv4 }}"
    prefix              : "{{ item[1].prefix }}"
    port_mode           : "{{ item[3].match[0] }}"
    mtu                 : "{{ item[2].match[0] }}"
    duplex              : "{{ item[4].duplex }}"
    admin_state         : "{{ item[5].admin }}"
    description         : "{{ item[6].match[0] }}"
    mac                 : "{{ item[7].match[0] }}"
    speed               : "{{ item[4].speed }}"
    input_rate_bits     : "{{ item[8].match[0] }}"
    output_rate_bits    : "{{ item[9].match[0] }}"
    input_rate_packets  : "{{ item[8].match[1] }}"
    output_rate_packets : "{{ item[9].match[1] }}"
    link_protocol_state : "{{ item[10].lineproto }}"
    bandwidth           : "{{ item[11].bw}} {{item[11].bwunit }}"
    mediatype           : "{{ item[12].medtype }}"
    linktype            : "{{ item[13].linktype }}"
    type                : "{{ item[14].type }}"

keys:
  interfaces:
    value: "{{ interface }}"
    start_block: "\\w{0,20}?((Serial|Ethernet).*[/]\\d+|Vlan\\d*)" # for Serial or X-Ethernet
                # "(\w{0,20}?(Serial|Ethernet)\d[/]\d+|Vlan)" # all
                #  "^\w+Ethernet.+$"    #for X-Ethernet only
                #  "^FastEthernet.+$"   #for fastethernet only
                #  "^Ethernet.+$"   #for ethernet only
                #  "^Serial.+$"   #for serial only
    end_block: ".+interface reset"
                #"(\\w? buffers swapped out|\\w? CTS=\\w*)"  # for Serial or X-Ethernet
                #  ".+interface reset" #all 
                # "(\w? buffers swapped out|\w? CTS=\w*)\v(\w+Ethernet\w+/|Vlan1 |Serial0/0)"  #for X-Ethernet only
                # "(\w? buffers swapped out|\w? CTS=\w*)\v(Ethernet\w+/|Vlan1 |Serial0/0)"  #for Ethernet only
                # "(\w? buffers swapped out|\w? CTS=\w*)\v(FastEthernet\w+/|Vlan1 |Serial0/0)"  #for fastethernet only
                # "\w? CTS=\w*"  #for serial only
    items:
      - "(?P<name>\\w+.*/\\d+|Vlan\\w+) is (?P<oper>[a-zA-Z ]*),"
      - "\\s+Internet address is (?P<ipv4>.+)/(?P<prefix>\\d*)"
      - "\\s+ MTU (\\d+)"
      - "\\s+Port mode is (\\w+)"
      - "  (?P<duplex>[a-zA-Z- ]+plex), (?P<speed>[0-9a-zA-Z-]+)"
      - "admin state is (?P<admin>\\w+)"
      - "Description: (.+)"
      - "is (\\w+\\.\\w+\\.\\w+)"
      - "input rate (\\d+) bits/sec, (\\d+) packets/sec"
      - "output rate (\\d+) bits/sec, (\\d+) packets/sec"
      - "line protocol is (?P<lineproto>\\w*)"
      - "BW (?P<bw>\\d*) (?P<bwunit>[a-zA-Z/]*)"
      - "media type is (?P<medtype>\\w*)"
      - "link type is (?P<linktype>\\w*)"
      - "Hardware is (?P<type>[a-zA-Z0-9 ]*)"