---
- name: Managament migration phase 1 Test 
  hosts: myaccess
  gather_facts: no
  serial: 1
  gather_timeout: 60
  connection: network_cli
  ignore_errors: no
  vars_files:
    - vars/common.yml 
  roles:
    - name: "First role"
      role: network_inspect
    - name: "Second role"
      role: variable_inspect
    # - name: "Third role"
    #   role: network_mgmn
  tasks:
    - debug:
        msg: "access - imported success {{inventory_hostname}} -  {{hostname}}"
- name: Managament migration phase 2 Test 
  hosts: mydist
  gather_facts: no
  serial: 1
  gather_timeout: 60
  connection: network_cli
  ignore_errors: no
  vars_files:
    - vars/common.yml 
  roles:
    - name: "First role"
      role: network_inspect
    - name: "Second role"
      role: variable_inspect
    # - name: "Third role"
    #   role: network_mgmn
  tasks:
    - debug:
        msg: "distribution - imported success {{inventory_hostname}} -  {{hostname}}"
- name: Managament migration phase 3 Test 
  hosts: mycore
  gather_facts: no
  serial: 1
  gather_timeout: 60
  connection: network_cli
  ignore_errors: no
  vars_files:
    - vars/common.yml 
  roles:
    - name: "First role"
      role: network_inspect
    - name: "Second role"
      role: variable_inspect
    # - name: "Third role"
    #   role: network_mgmn
  tasks:
    - debug:
        msg: "core - imported success {{inventory_hostname}} -  {{hostname}}"