---
- name: Automation Project
  hosts: test
  gather_facts: no
  gather_timeout: 60
  ignore_errors: no
  connection: local
  vars_files:
    - vars/test.yml
  pre_tasks:
    - name: test PING to host
      ping:
          data: pong 
    - set_fact:
        host_ip: "{{ansible_host}}"
        username: "{{ansible_ssh_user}}"
        password: "{{ansible_ssh_pass}}"
    - debug:
        msg: "{{host_ip}} {{username}} {{password}}"

    - name: test PING reachability using default vrf
      ios_ping:
        dest: 10.240.192.1
        provider:
          password: "{{password}}"
          username: "{{username}}"
          timeout: "{{ timeout }}"
          host: "{{host_ip}}"
      delay: "{{ delay }}"
      retries: "{{ retries }}"
      register: test_ping
    - set_fact:
        password: "{{new_ansible_ssh_pass}}"
      when: password!=new_ansible_ssh_pass
    - set_fact:
        username: "{{new_ansible_ssh_user}}"
      when: username!=new_ansible_ssh_user
    - debug:
        msg: "{{host_ip}} {{username}} {{password}}"   

         

