
- name: Include - add vlan task
  include_tasks: add_vlan.yml
  when: phase == "one" 
- name: Include - add switchport task
  include_tasks: add_switchport.yml
  when: phase == "two" 
- name: Include - add ip task
  include_tasks: add_ip.yml
  when: phase == "three" 
- name: Include - delete old and use new connection
  include_tasks: delete.yml
  when: phase == "four" 