# sw_ku3_b3#sh ip dhcp server statistics
# Memory usage         5956

# Address pools        4
# Database agents      0
# Automatic bindings   0
# Manual bindings      0
# Expired bindings     0
# Malformed messages   0
# Secure arp entries   0

# Message              Received
# BOOTREQUEST          0
# DHCPDISCOVER         0
# DHCPREQUEST          0
# DHCPDECLINE          0
# DHCPRELEASE          0
# DHCPINFORM           0

# Message              Sent
# BOOTREPLY            0
# DHCPOFFER            0
# DHCPACK              0
# DHCPNAK              0
