# sw_ku3_b3#sh ip dhcp binding
# Bindings from all pools not associated with VRF:
# IP address          Client-ID/              Lease expiration        Type
#                     Hardware address/
#                     User name

vars:
  vlan:
    id: "{{ item.id }}"
    name: "{{ item.name }}"
    status: "{{ item.status }}"
    ports: "{{ (item.ports|replace('Gi', 'GigabitEthernet') | replace('Po','PortChannel')).split(', ') }}"

keys:
  vlans:
    value: "{{ vlan }}"
    items: "^(?P<id>\\d+)\\s+(?P<name>\\S+)\\s+(?P<status>[a-z]{4,})\\s*(?P<ports>([A-Za-z]+).+)?"