# sw_ku3_b3#sh ip dhcp binding
# Bindings from all pools not associated with VRF:
# IP address          Client-ID/              Lease expiration        Type
#                     Hardware address/
#                     User name

vars:
  binding:
    ip_addr: "{{item.a}}"
    client_id: "{{item.b}}"
    lease_exp: "{{item.c}}"
    type: "{{item.d}}"

keys:
  dhcp_binding:
    value: "{{ binding }}"
    items: "^(?P<a>(\\d*[.]*){4,})\\s*(?P<b>Hardware address/)($|\\s*(?P<c>[a-zA-Z0-9]*)\\s*(?P<d>[a-zA-Z0-9]*))"