# sw_ku3_b3#sh ip dhcp conflict
# IP address        Detection method   Detection time          VRF
#

vars:
  conflict:
    ip_addr: "{{item.a|default('na,true)}}"
    detection_method: "{{item.b|default('na',true)}}"
    detection_time: "{{item.c|default('na',true)}}"
    vrf: "{{item.d|default('na',true)}}"

keys:
  dhcp_conflict:
    value: "{{ conflict }}"
    items: "^(?P<a>\\d\\S*)\\s*(?P<b>\\S*)\\s*(?P<c>\\S*)\\s*(?P<d>\\S*)"
   
