ansible_host: 10.240.192.10
hostname: sw_ku3_a1
hierarchy_layer: access
alias:
  - access: &a access
  - trunk: &t trunk
dhcp_pool:
  - WIFI_A_LT0A
  - WIFI_B_LT0A
vty:
    - vty04
    - vty515
user:
  master: cisco2     
  # master hanya berjumlah satu, apa perlu backup user??
  whitelist:
    - sisfo
    - widi
    - diazzaid
    - cuman
    - sakti
  # level privilege user bebas sesuai di userdb
  blocked:
    - baba
    - abu
    - caca
vlan:
  by_name:  # Vlan can not be added. Maximum number of 32 vlan(s) in the database.
    - RFID-LT1A               #901
    - CAMERA-LT1A             #902
    - LAN-PPDU-BAA           #903
    - WIFI-A-LT1A             #904
    - WIFI-B-LT1A             #908
    - vlan-mgmn-dev           #1097
    - vlan-mgmn-ap            #1098
    - scn-superVlan-Wirele    #1099
    - network-chrome          #3154
interface:
  - name: FastEthernet0/0    #reserveda
  - name: FastEthernet0/1    #reserved
    duplex: full
    speed: 100
    mtu: 1500
    description: 
  - name: FastEthernet1/0    #901
    mode: *a
    duplex: full
    speed: 100
    mtu: 1500
    description: 
    access_vlan: &RFID-LT1A   "{{ vlan_db | json_query('[?name==`RFID-LT1A`].vlan_id') | join ()| default(901, true) }}"
  - name: FastEthernet1/1    #901
    mode: *a
    duplex: full
    speed: 100
    mtu: 1500
    description: 
    access_vlan: *RFID-LT1A
  - name: FastEthernet1/2    #901
    mode: *a
    duplex: full
    speed: 100
    mtu: 1500
    description: 
    access_vlan: *RFID-LT1A
  - name: FastEthernet1/3    #901
    mode:  *a 
    duplex: full
    speed: 100
    mtu: 1500
    description:
    access_vlan: *RFID-LT1A
  - name: FastEthernet1/4    #901
    mode:  *a 
    duplex: full
    speed: 100
    mtu: 1500
    description:
    access_vlan: *RFID-LT1A
  - name: FastEthernet1/5    #3104 bpduguard spanning tree, protected
    mode:  *a 
    duplex: full
    speed: 100
    mtu: 1500
    description:
    access_vlan: &VLANNAME3104   "{{ vlan_db | json_query('[?name==`VLANNAME3104`].vlan_id') | join ()| default(3104, true) }}"
  - name: FastEthernet1/6    #3104 bpduguard spanning tree, protected
    mode:  *a 
    duplex: full
    speed: 100
    mtu: 1500
    description:
    access_vlan: *VLANNAME3104
  - name: FastEthernet1/7    #3104 bpduguard spanning tree, protected
    mode:  *a 
    duplex: full
    speed: 100
    mtu: 1500
    description: BAA
    access_vlan: *VLANNAME3104
  - name: FastEthernet1/8    #902
    mode:  *a 
    duplex: full
    speed: 100
    mtu: 1500
    description:
    access_vlan: &CAMERA-LT1A   "{{ vlan_db | json_query('[?name==`CAMERA-LT1A`].vlan_id') | join ()| default(902, true) }}"
  - name: FastEthernet1/9    #902
    mode:  *a 
    duplex: full
    speed: 100
    mtu: 1500
    description:
    access_vlan: *CAMERA-LT1A
  - name: FastEthernet1/10   #1098 
    mode:  *t 
    duplex: full
    speed: 100
    mtu: 1500
    description: PPDU
    trunk_vlan: &vlan-mgmn-ap   "{{ vlan_db | json_query('[?name==`vlan-mgmn-ap`].vlan_id') | join ()| default(1098, true) }}"
  - name: FastEthernet1/11   #1098 
    mode:  *t 
    duplex: full
    speed: 100
    mtu: 1500
    description:
    access_vlan: *vlan-mgmn-ap
  - name: FastEthernet1/12   #1098 
    mode:  *t 
    duplex: full
    speed: 100
    mtu: 1500
    description:
    trunk_vlan: *vlan-mgmn-ap
  - name: FastEthernet1/13   #reserved
  - name: FastEthernet1/14   #mode trunk
    mode:  *t 
    duplex: full
    speed: 100
    mtu: 1500
    description: uplink
    allowed: 1095,1957,3101-3102,3104,3151-3152
    add: 3152,3154
  # - name: FastEthernet1/15   #mode trunk
  #   mode:  *t 
  #   duplex: full
  #   speed: 100
  #   mtu: 1500
  #   description: uplink
  #   allowed: 1095,1957,3101-3102,3104,3151-3152
  #   add: 3152,3154
  - name: vlan 1             #no-ip
    ip: no
  - name: vlan 1097          #ip
    ip: 10.240.192.10
    subnet: 255.255.0.0
    prefix: 16
services_on:
  - no service pad
  - service timestamps debug datetime msec localtime
  - service timestamps log datetime localtime
  - no service password-encryption
  - hostname SW.KU3.01.ZONA-A
  - boot-start-marker
  - boot-end-marker
  - no aaa new-model
  - clock timezone UTC 7 0
  - vtp mode transparent
  - no spanning-tree vlan 901
  - errdisable detect cause bpduguard 
  - errdisable recovery cause bpduguard
  - ip default-gateway 192.240.0.1
  - no ip http server
  - no ip http secure-server
  - logging trap debugging
  - logging facility syslog
  - logging host 192.168.101.3 
  - snmp-server community oraora RO
  - snmp-server location GKU-LT1A
  - snmp-server contact NOC_Tel-U

services_off:
crypto:

    # sw_ku3_a1:
    #   vty:
    #     - vty04
    #     - vty515
    #   dhcp_pool:
    #     - WIFI_A_LT0A
    #     - WIFI_B_LT0A
    #   user:
    #     master: cisco2     
    #     # master hanya berjumlah satu, apa perlu backup user??
    #     whitelist:
    #       - sisfo
    #       - widi
    #       - diazzaid
    #       - cuman
    #       - sakti
    #     # level privilege user bebas sesuai di userdb
    #     blocked:
    #       - baba
    #       - abu
    #       - caca
    #   vlan:
    #     by_name:
    #       - RFID-LT1A               #901
    #       - CAMERA-LT1A             #902
    #       - LAN-PPDU-BAA           #903
    #       - WIFI-A-LT1A             #904
    #       - WIFI-B-LT1A             #908
    #       - vlan-mgmn-dev           #1097
    #       - vlan-mgmn-ap            #1098
    #       - scn-superVlan-Wirele    #1099
    #       - network-chrome          #3154
    #     by_id:
    #       - 1095,1957,3101-3102,3104,3151-3152
    #       - 901
    #       - 902
    #       - 903
    #       - 904
    #       - 908
    #       - 1095
    #       - 1097
    #       - 1098
    #       - 1099
    #       - 3101
    #       - 3102
    #       - 3104
    #       - 3151
    #       - 3152
    #       - 3154
    #   interface:
    #     - name: fa0/0
    #     - name: fa0/1
    #     - name: fa1/0
    #       mode: access
    #       vlan: 901
    #     - name: fa1/1
    #       mode: access
    #       vlan: 901
    #     - name: fa1/2
    #       mode: access
    #       vlan: 901
    #     - name: fa1/3
    #       mode: access
    #       vlan: 901
    #     - name: fa1/4
    #       mode: access
    #       vlan: 901
    #     - name: fa1/5
    #     - name: fa1/6
    #     - name: fa1/7
    #     - name: fa1/8
    #       mode: access
    #       vlan: 902
    #     - name: fa1/9
    #       mode: access
    #       vlan: 902
    #     - name: fa1/10
    #       mode: trunk native
    #       vlan: 1098
    #     - name: fa1/11
    #       mode: trunk native
    #       vlan: 1098
    #     - name: fa1/12
    #       mode: trunk native
    #       vlan: 1098
    #     - name: fa1/13
    #     - name: fa1/14
    #     - name: fa1/15
    #       mode: trunk
    #       allow: 1,901,1095,1097,1098,1957,3101,3102,3104,3151
    #       add: 3152,3154
    #     - name: vlan1
    #       ip: no
    #     - name: vlan1097
    #       ip: 10.168.192.10
    #       subnet: 255.255.0.0
    #       prefix: 16

    #       # // karena interface terbatas dari fa1/0 hingga fa1/15 total ada 16 tapi saya gunakan 14 saja dan menadi sebagai berikut//
    #       # 901=IntFa1/0-4 access

    #       # 902=IntFa1/8-9 access
    #       # 1098=IntFa1/10-12 trunk native

    #       # ip dhcp snooping trust
    #       # trunk allow 1,901,1095,1097,1098,1957,3101,3102,3104,3151,
    #       # vlan add  3152,3154 = intFa1/15

    #       # IntVlan1=no ip
    #       # IntVlan1097= 192.240.192.10/24
    #       # IntF0/0=192.168.1.1/24
    #   services_on:
    #     - no service pad
    #     - service timestamps debug datetime msec localtime
    #     - service timestamps log datetime localtime
    #     - no service password-encryption
    #     - hostname SW.KU3.01.ZONA-A
    #     - boot-start-marker
    #     - boot-end-marker
    #     - no aaa new-model
    #     - clock timezone UTC 7 0
    #     - switch 1 provision ws-c2960xr-24ps-i
    #     - system mtu routing 1500
    #     - ip dhcp snooping vlan 3101,3104
    #     - ip dhcp snooping
    #     - vtp mode transparent
    #     - spanning-tree mode pvst
    #     - spanning-tree extend system-id
    #     - no spanning-tree vlan 1,901
    #     - errdisable detect cause bpduguard shutdown vlan
    #     - errdisable recovery cause bpduguard
    #     - vlan internal allocation policy ascending
    #     - ip default-gateway 192.240.0.1
    #     - no ip http server
    #     - no ip http secure-server
    #     - logging trap debugging
    #     - logging facility syslog
    #     - logging host 192.168.101.3 #10.13.10.30
    #     - snmp-server community oraora RO
    #     - snmp-server location GKU-LT1A
    #     - snmp-server contact NOC_Tel-U
    #   services_off:
    #   crypto:

      