#NEED MORE TEST

---
  - name: Include var
    include_vars: pooldb3.yml

  - name: "setup dhcp excluded-address based on pool "
    ios_config:  
      lines:
        - ip dhcp excluded-address {{item.1}}
      provider:
        timeout: "{{ timeout }}"
    loop: "{{ pooldb3 | subelements('excluded') }}"  
    loop_control:
      label: "{{ item.0.name}}"
    when: item.0.name in dhcp_pool
    delay: "{{ delay }}"
    retries: "{{ retries }}"
    ignore_errors: yes
    register: result_excluded
    until: result_excluded.changed == false  
  # - debug:
  #     var: result_excluded #variable , ugh i should get status for reporting not from my variable
  #     verbosity: "{{ set_verbosity }}"
  - name: "setup dhcp pool v3"
    ios_config:
      lines:
        - network {{ pooldb3[item].ipv4.network | ipv4}} {{ pooldb2[item].ipv4.subnet | ipv4}}
        - dns-server {{ pooldb3[item].dns-server | default ("10.252.252.4 10.252.252.5")}} 
        - default-router {{ pooldb3[item].ipv4.default_router }}
        - domain-name {{ pooldb3[item].domain-name }}
        - lease {{ pooldb3[item].lease.days | default (0)}} {{ ppooldb3[item].lease.hours | default (2) }}
      parents:
        - ip dhcp pool {{ pooldb3[item].name }}
    loop:  "{{range(0, (pooldb3 | length), 1)| list}}"  
    loop_control:
      label: "{{ pooldb3[item].name  }}"
    when: pooldb3[item].name in dhcp_pool
    delay: "{{ delay }}"
    retries: "{{ retries }}"
    ignore_errors: yes
    register: result_dhcp
    until: result_dhcp.changed == true 
  # - debug:
  #     var: result_dhcp #variable , ugh i should get status for reporting not from my variable
  #     verbosity: "{{ set_verbosity }}"
      
    