---
  - name: Include var
    include_vars: pooldb2.yml

  # - name: "setup dhcp excluded-address based on pool for {{hostname}}"
  #   debug :  
  #     var: item.0.name
  #   loop: "{{ pooldb2 | subelements('excluded') }}" 
  #   loop_control:
  #     label: "{{ item.0.name}}"
  - name: "setup dhcp excluded-address based on pool "
    ios_config:  
      lines:
        - ip dhcp excluded-address {{item.1}}
    loop: "{{ pooldb2 | subelements('excluded') }}"  
    loop_control:
      label: "{{ item.0.name}}"
    when: item.0.name in dhcp_pool
    delay: "{{ delay }}"
    retries: "{{ retries }}"
    ignore_errors: yes
    register: result_excluded
    until: result_excluded.changed == false  
  # - debug:
  #     var: result_excluded #variable , ugh i should get status for reporting not from my variable
  #     verbosity: "{{ set_verbosity }}"
  - name: "setup dhcp pool for {{hostname}}"
    ios_config:
      lines:
        - network {{ pooldb2[item].ipv4_network | ipv4}} {{ pooldb2[item].ipv4_subnet | ipv4}}
        - dns-server {{ dns1 | default ("10.252.252.4")}} {{ dns2 | default ("10.252.252.5") }}
        - default-router {{ pooldb2[item].default_router }}
        - domain-name {{ mydomain }}
        - lease {{ pooldb2[item].lease_days | default (2)}} {{ pooldb2[item].lease_hours | default (2) }}
      parents:
        - ip dhcp pool {{ pooldb2[item].name }}
    loop:  "{{range(0, (pooldb2 | length), 1)| list}}"  
    loop_control:
      label: "{{ pooldb2[item].name  }}"
    when: pooldb2[item].name in dhcp_pool
    delay: "{{ delay }}"
    retries: "{{ retries }}"
    ignore_errors: yes
    register: result_dhcp
    until: result_dhcp.changed == true 
  # - debug:
  #     var: result_dhcp #variable , ugh i should get status for reporting not from my variable
  #     verbosity: "{{ set_verbosity }}"
      
    